### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by W4RH4WK** [atishay/vscode-allautocomplete#12] opened 2017-12-05 12:06 UTC
Similar to #11 I also have this error in my console.

```
[Atishay-Jain.All-Autocomplete] Cannot read property 'split' of undefined: TypeError: Cannot read property 'split' of undefined
	at Function.replace (C:\Users\alex\.vscode\extensions\Atishay-Jain.all-autocomplete-0.0.10\out\src\extension.js:112:25)
	at e.contentChanges.forEach (C:\Users\alex\.vscode\extensions\Atishay-Jain.all-autocomplete-0.0.10\out\src\extension.js:139:41)
	at Array.forEach (native)
	at Function.handleContextChange (C:\Users\alex\.vscode\extensions\Atishay-Jain.all-autocomplete-0.0.10\out\src\extension.js:138:26)
	at context.subscriptions.push.vscode_1.workspace.onDidChangeTextDocument (C:\Users\alex\.vscode\extensions\Atishay-Jain.all-autocomplete-0.0.10\out\src\extension.js:224:30)
	at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:84411)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:86133)
	at e.$acceptModelChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:427937)
	at t.e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:509443)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:354786)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:354476)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:353503
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:355422
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:85128
	at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:84411)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:86133)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:144114)
```

**Comment by atishay** [comment] 2017-12-16 20:24
@W4RH4WK Can you please verify in v 0.0.11. I am not able to reproduce the bug. But added a check. This one was a safe check.

**Comment by atishay** [comment] 2018-01-14 07:30
Closing as cannot reproduce.

**Closed by atishay** 2018-01-14 07:30 UTC
