### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by W4RH4WK** [atishay/vscode-allautocomplete#11] opened 2017-12-05 12:06 UTC
While the extension is working, I observed the following errors in the console.

```
[Atishay-Jain.All-Autocomplete] Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
	at DocumentManagerClass.clearDocument (C:\Users\alex\.vscode\extensions\Atishay-Jain.all-autocomplete-0.0.10\out\src\DocumentManager.js:86:33)
	at context.subscriptions.push.vscode_1.workspace.onDidCloseTextDocument (C:\Users\alex\.vscode\extensions\Atishay-Jain.all-autocomplete-0.0.10\out\src\extension.js:217:43)
	at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:84411)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:86133)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:426225
	at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:84411)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:86133)
	at e.$acceptDocumentsAndEditorsDelta (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:430292)
	at t.e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:509443)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:354786)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:354476)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:353503
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:355422
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:85128
	at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:84411)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:86133)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:144114)
```

**Comment by atishay** [comment] 2017-12-06 15:26
Thanks for the information. I will try and see what has changed in vscode and will reply back in a day or two.

**Comment by atishay** [comment] 2017-12-18 05:25
@W4RH4WK I am not able to reproduce this one. Unlike #12, this one does impact functionality. I would love to know how to get it reproduced. Do you have some special type of file open. Are there steps to reproduce the issue?

**Comment by W4RH4WK** [comment] 2017-12-18 13:07
I am currently unable to reproduce this (and also #12). Maybe the new VSCode release fixed something causing this problem, yet I do not know.

I'll notify you if I find a reliable way to reproduce any one of these 2 issues.

**Comment by atishay** [comment] 2018-01-14 07:30
Closing as non-reproducible.

**Closed by atishay** 2018-01-14 07:30 UTC
